### ISSUE TITLE
Custom font to support cjk character

### ISSUE THREAD

**Issue by CUexter** [Signez/balatro-sprites-i18n#6]
Hi thanks for the project. However I would like to add fonts for the project to use, yet it seems like no matter how hard i try, sharp fails to read my font. How do i make it work ?

**Comment by Signez** [comment]
Hey! I am not surprised you encountered some trouble with sharp handling of fonts: it seems to be quite brittle… 

Here, in this file:

https://github.com/Signez/balatro-sprites-i18n/blob/c0dc2bc4d2304090e5d827f2bdab9037df60cb9f/src/tarots.js#L50-L55

I specify the font to use _twice_: using both it's name on line 52 (`Balatro Extended (Consumable Cards)`) and on line 54 by referencing the `fontPath`.

Did you try to change both of those variables at once? On my Mac-based workstation, it was necessary to change both of those variables to make it understand which font I wanted to use. If you already tried that, on what platform are you trying to run the pipeline? What did you try?

**Comment by CUexter** [comment]
how do i know the name of the font ? I have a ttf file. I am running on Linux.

**Comment by CUexter** [comment]
More specifically how do i know if sharp is able to find the font ?

**Comment by Signez** [comment]
> how do i know the name of the font ? I have a ttf file. I am running on Linux.

You can use some online font inspector, like [FontDrop](https://fontdrop.info/).

> More specifically how do i know if sharp is able to find the font ?

Does it show an error? It didn't in my case; it fallbacked to an Arial-like font. Is it what you encounter?

**Comment by CUexter** [comment]
i figured out I have to specify the style and size in the font name. Maybe it is system specific ? Idk. I managed to fix the problem by adjusting dpi and stuff.

Do you know when will the game use 1x assets, they look terrible for Chinese

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by woctezuma** [comment]
> Do you know when will the game use 1x assets, they look terrible for Chinese

If I remember right, this is linked to the setting for `Pixel Art Smoothing`:
- if the setting is toggled `Off`, the game uses `1x` assets,
- if the setting is toggled `On`, the game uses `2x` assets.

```lua
b_set_pixel_smoothing = "Pixel Art Smoothing",
ml_smoothing_opt = { "Off", "On" },
```
